### ISSUE TITLE
Założyć i skonfigurować Firebase

### ISSUE THREAD

**Issue by copy-on-meow** [siag-sggw/stockapp#1]
[Link](https://firebase.google.com)

**Comment by odisei369** [comment]
Nie ma nazwy appki formatu `com.firebase.ourApp`.
Czy mogę wziąć dowolne a osoba zakładająca repo dostosuje się?

**Comment by odisei369** [comment]
Założyłem że nazwa app `pl.sggw.stock`.
Actywowałem logowanie i rejestrację przez mail.
Tu tutorial jak to podpiąć do appki https://www.youtube.com/watch?v=n9cClPtxUk0
Załaczam pliki konfiguracyjne.
Konfiguracja osobnie wrzuca się w appkę iOS i osobno Android.
[firebase.zip](https://github.com/siag-sggw/stockapp/files/2499404/firebase.zip)
